name: uspsa_result_viewer
description: A USPSA match result viewer and Elo rater.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 6.4.8+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  fluro: ^2.0.3 # routing
  http: ^0.13.6 # web requests
  collection: ^1.17.0
  file_picker: ^5.2.4
  url_launcher: ^6.0.2
  sprintf: ^7.0.0
  intl: ^0.17.0
  flutter_charts: ^0.5.0
  charts_flutter: # new charts
    git:
      url: https://github.com/jslater89/charts_flutter
      ref: master
      path: charts_flutter
  shared_preferences:
  path_provider: ^2.0.15
  sanitize_filename: ^1.0.4
  normal: ^0.6.0
  fluttericon: ^2.0.0
  google_fonts: ^2.2.0
  flutter_typeahead: ^4.1.1
  hive: 2.2.3
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  floor: ^1.3.0
  fuzzywuzzy: ^0.2.0
  html_unescape: ^2.0.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.0
  build_runner: ^2.2.0
  hive_generator: ^2.0.0

flutter_icons:
  android: false
  ios: false
  image_path: "assets/icon.png"
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#ffffff"
    theme_color: "#c19a6c"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 256


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
