/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

import 'package:shooting_sports_analyst/data/help/help_topic.dart';

const ratingReportsHelpId = "rating_reports";
const ratingReportsHelpLink = "?rating_reports";
final helpRatingReports = HelpTopic(
  id: ratingReportsHelpId,
  name: "Rating reports",
  content: _content,
);

const _content =
"""# Rating reports

Rating reports are advisory notices generated by the rating engine during calculations.
The list of reports may be filtered by rating group, type, or severity, and may be
toggled between recent reports (those that occurred during the last calculation,
whether full or partial), and all reports (all unique reports that have occurred
since the last full recalculation). Each report may be expanded to show more details.

In general, info-level reports point out data issues that only potentially represent
inconsistencies. For example, a common info-level report notifies you that there are
multiple names for one member number with a large string difference. In some cases
(John Doe and John "Super Cool Nickname" Doe), this needs no further action.

Warning reports indicate that there are data inconsistencies that are likely to
impact rating accuracy, or inconsistencies in member number mapping data. Common warning
reports include:
* The rating engine attempted to deduplicate a member number, but the proposed fixes
  were already saved in the project's settings, which indicates a likely deduplicator bug.
* There is a conflict in the project settings, for example a member number mapping that also
  appears in the project's blacklist.

Severe reports indicate that data inconsistencies are definitely causing issues
with rating accuracy, but the rating engine did not detect them during the calculation.
Severe reports include:
* A data entry fix loop was detected: A123456 → L1234 → A123456. This may indicate a bug
  in the deduplicator, or incorrect entry of data entry fixes. Correcting the data entry
  fixes will be necessary to resolve this issue.
* Two ratings were merged because of a member number mapping, but both ratings had rating
  data at the time of the merge. During the merge, the rating engine preserved the data
  from the rating with the longest history, and discarded the data from the other rating.
  A full recalculation is likely to resolve this issue.
""";
